### ISSUE TITLE
Cannot extract data of "Kami-sama no You na Kimi e - Extended Edition"

### ISSUE THREAD

**Issue by sum2012** [arcusmaximus/KirikiriTools#11]
https://vndb.org/r87754
Thanks.

**Comment by sum2012** [comment]
Work with https://github.com/xmoeproject/KrkrzExtract
Closing

**Comment by sum2012** [comment]
The game is  used for KirikiriZ
![1](https://user-images.githubusercontent.com/2177532/176972696-3a498cd3-10e8-4587-bb40-848c913a02db.png)

KrkrzExtract can extract all file except *.tlg file.

**Comment by sum2012** [comment]
This one extract perfect.No need to play whole game
https://github.com/Kerisa/ExtractGames/tree/master/kirikiri

**Comment by arcusmaximus** [comment]
@Cosetto KirikiriZ is just a modernized version of Kirikiri and still uses .ks files. The .scn format is not supported by Kirikiri(Z) itself and requires an external plugin to work (psbfile.dll). For as far as I know, it's only found in games developed by Wamsoft. The incorrect association that "KirikiriZ uses .scn" probably exists due to the sheer amount of games that they're behind.

In the end it doesn't matter for this issue, though - whether the game uses .ks or .scn bears no relation to how its .xp3 archives are encrypted.

The extraction feature of KirikiriUnencryptedArchive is really meant as a last resort in case no other tool works - it's definitely not meant to be a full replacement for KrkrExtract and the like. I added a note in the readme to point this out.

**Comment by fkvldh** [comment]
> This one extract perfect.No need to play whole game https://github.com/Kerisa/ExtractGames/tree/master/kirikiri

How I use it?

**Comment by sum2012** [comment]
loader.exe game.exe  <xp3 file 1> <xp3 file2> ...
> > This one extract perfect.No need to play whole game https://github.com/Kerisa/ExtractGames/tree/master/kirikiri
> 
> How I use it?

**Comment by fkvldh** [comment]
> loader.exe game.exe <xp3 file 1> xp3 file2
> 
> > > This one extract perfect.No need to play whole game https://github.com/Kerisa/ExtractGames/tree/master/kirikiri
> > 
> > 
> > How I use it?

Thank you.
Sadly, It's not work...

**Comment by sum2012** [comment]
Not work
> > loader.exe game.exe <xp3 file 1> xp3 file2
> > > > This one extract perfect.No need to play whole game https://github.com/Kerisa/ExtractGames/tree/master/kirikiri
> > > 
> > > 
> > > How I use it?
> 
> How about "AMBITIOUS MISSION"? It's work? https://vndb.org/v33036

**Comment by sum2012** [comment]
I have created the (first !!!) issue  in their project
> > loader.exe game.exe <xp3 file 1> xp3 file2
> > > > This one extract perfect.No need to play whole game https://github.com/Kerisa/ExtractGames/tree/master/kirikiri
> > > 
> > > 
> > > How I use it?
> 
> How about "AMBITIOUS MISSION"? It's work? https://vndb.org/v33036
